#!/bin/zsh -f
emulate -L zsh
if whence __doz-load >/dev/null; then
else
  builtin autoload -Uz __doz-load && __doz-load
fi

function (){
  local out sel
  out="$(__doz-deno)"
  if [[ $? -ne 0 ]]; then
    echo
  fi
  if [[ -n "$out" ]]; then
    sel=$(echo "$out" | fzf --prompt='doz > ' --exact)
    if [[ -n "$sel" ]]; then
      if [[ ! "$LBUFFER" =~ ' $' ]]; then
        LBUFFER="$LBUFFER "
      fi
      LBUFFER="$LBUFFER$(echo "$sel" | cut -f 1) "
    fi
  fi
  zle reset-prompt
}
