#!/bin/zsh -f
emulate -L zsh

function (){
  local out
  out="$(__exhint-get-hints)"
  if [[ $? -ne 0 ]]; then
    echo
  fi
  if [[ -n "$out" ]]; then
    echo
    echo "$out"
  fi
  zle reset-prompt
}
