#!/bin/zsh -f
emulate -L zsh
if whence __shdo-load >/dev/null; then
else
  builtin autoload -Uz __shdo-load && __shdo-load
fi

function (){
  local out
  out="$(__shdo-deno)"
  if [[ $? -ne 0 ]]; then
    echo
  elif [[ -z "$out" ]]; then
    zle reset-prompt
    return
  fi

  local outary=("${(f)out}")
  local argv="${(F)${(@)outary[1,-2]}}"
  local ftail="${outary[-1]}"
  local ext file
  for ext in zsh sh; do
    if [[ -f "$ftail.$ext" ]]; then
      file="$ftail.$ext"
      break
    fi
  done
  if [[ -z "$file" ]]; then
    __shdo-print "fail in loading kind file: \`$ftail.{zsh,sh}\`"
  fi
  source "$file"
  zle reset-prompt
}
