#!/bin/zsh -f
emulate -L zsh

function (){
  local out sel
  out="$(__subhint-get-hints)"
  if [[ $? -ne 0 ]]; then
    echo
  fi
  if [[ -n "$out" ]]; then
    sel=$(echo "$out" | fzf --prompt='subhint > ')
    if [[ -n "$sel" ]]; then
      if [[ ! "$LBUFFER" =~ ' $' ]]; then
        LBUFFER="$LBUFFER "
      fi
      LBUFFER="$LBUFFER$(echo "$sel" | cut -f 1) "
    fi
  fi
  zle reset-prompt
}
